name:
  cdk_action

on:
  push

permissions:
  id-token: write
  contents: read

jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      - name: aws cli install
        run: |
          pip install awscli --upgrade --user 
          pip install aws-cdk-lib==2.65.0   
          npm install -g aws-cdk
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} 
          role-session-name: samplerolesession
          aws-region: ap-northeast-1
      - name: deploy
        run: |
          cd cdk_workshop
          cdk deploy --require-approval "never"
          # cdk destroy --require-approval "never"